const C={nominatim:"https://nominatim.openstreetmap.org/search",ttl:86400000,max:24,debounce:450};
const COUNTRY_CITIES={YE:[["صنعاء","Sanaa",15.3694,44.191],["عدن","Aden",12.7855,45.0187],["تعز","Taiz",13.5795,44.0209],["الحديدة","Al Hudaydah",14.7978,42.9545],["إب","Ibb",13.9667,44.1833],["المكلا","Al Mukalla",14.5425,49.1242]],SA:[["الرياض","Riyadh",24.7136,46.6753],["جدة","Jeddah",21.4858,39.1925],["مكة","Mecca",21.3891,39.8579],["المدينة المنورة","Medina",24.5247,39.5692]],AE:[["دبي","Dubai",25.2048,55.2708],["أبوظبي","Abu Dhabi",24.4539,54.3773],["الشارقة","Sharjah",25.3463,55.4209]],TR:[["إسطنبول","Istanbul",41.0082,28.9784],["أنقرة","Ankara",39.9334,32.8597],["أنطاليا","Antalya",36.8969,30.7133]],EG:[["القاهرة","Cairo",30.0444,31.2357],["الإسكندرية","Alexandria",31.2001,29.9187],["الأقصر","Luxor",25.6872,32.6396]],FR:[["باريس","Paris",48.8566,2.3522],["نيس","Nice",43.7102,7.262],["ليون","Lyon",45.764,4.8357]],IT:[["روما","Rome",41.9028,12.4964],["ميلانو","Milan",45.4642,9.19],["البندقية","Venice",45.4408,12.3155]],ES:[["مدريد","Madrid",40.4168,-3.7038],["برشلونة","Barcelona",41.3874,2.1686],["إشبيلية","Seville",37.3891,-5.9845]],GB:[["لندن","London",51.5074,-0.1278],["مانشستر","Manchester",53.4808,-2.2426],["إدنبرة","Edinburgh",55.9533,-3.1883]],US:[["نيويورك","New York",40.7128,-74.006],["لوس أنجلوس","Los Angeles",34.0522,-118.2437],["سان فرانسيسكو","San Francisco",37.7749,-122.4194]],DE:[["برلين","Berlin",52.52,13.405],["ميونخ","Munich",48.1351,11.582],["هامبورغ","Hamburg",53.5511,9.9937]],JP:[["طوكيو","Tokyo",35.6762,139.6503],["أوساكا","Osaka",34.6937,135.5023],["كيوتو","Kyoto",35.0116,135.7681]]};
const POPULAR=[["صنعاء","Sanaa","اليمن",15.3694,44.1910],["إسطنبول","Istanbul","تركيا",41.0082,28.9784],["القاهرة","Cairo","مصر",30.0444,31.2357],["باريس","Paris","فرنسا",48.8566,2.3522],["عدن","Aden","اليمن",12.7855,45.0187],["دبي","Dubai","الإمارات العربية المتحدة",25.2048,55.2708],["مكة","Mecca","المملكة العربية السعودية",21.3891,39.8579],["المدينة المنورة","Medina","المملكة العربية السعودية",24.5247,39.5692]];const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const S={results:[],timer:null,id:0,markers:[]};let map,layer;
function cg(k){try{const v=JSON.parse(localStorage.getItem("tour:"+k));if(v&&Date.now()-v.t<C.ttl)return v.d}catch{}return null}function cs(k,d){try{localStorage.setItem("tour:"+k,JSON.stringify({t:Date.now(),d}))}catch{}}
function score(r){return .34*(r.rating||0)/5+.24*Math.min(1,Math.log10((r.references||1)+1)/3)+.22*(r.viewsNorm||0)+.20*(r.recency||0)}
function hav(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function get(url,opts={}){const c=cg(url);if(c)return c;const r=await fetch(url+(url.includes("?")?"&":"?")+"v=3",opts);if(!r.ok)throw Error("HTTP "+r.status);const text=await r.text();const d=JSON.parse(text.replace(/^\uFEFF/, ""));cs(url,d);return d}
async function osm(q,countryCode=""){const u=C.nominatim+"?format=jsonv2&limit=20&q="+encodeURIComponent(q)+(countryCode?"&countrycodes="+encodeURIComponent(countryCode):"");const d=await get(u,{headers:{"Accept-Language":"ar"}});return d.map(x=>({name:x.display_name.split(",")[0],city:x.display_name.split(",")[1]?.trim()||"",country:x.display_name.split(",").at(-1)?.trim()||"",lat:+x.lat,lng:+x.lon,category:x.type||"place",references:3,rating:0,image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80"}))}
async function local(q){const code=$("#countryFilter").value;const nq=String(q||"").trim().toLowerCase();const rows=code?(COUNTRY_CITIES[code]||[]):Object.values(COUNTRY_CITIES).flat();const hits=rows.filter(x=>x[0].toLowerCase().includes(nq)||x[1].toLowerCase().includes(nq));if(hits.length)return hits.slice(0,C.max).map(x=>({name:x[0],city:x[0],country:$("#countryFilter option:checked")?.textContent||"",lat:x[2],lng:x[3],category:"city",references:5,rating:4.5}));if(code&&COUNTRY_CITIES[code])return COUNTRY_CITIES[code].slice(0,C.max).map(x=>({name:x[0],city:x[0],country:$("#countryFilter option:checked")?.textContent||"",lat:x[2],lng:x[3],category:"city",references:5,rating:4.5}));return POPULAR.filter(x=>x[0].toLowerCase().includes(nq)||x[1].toLowerCase().includes(nq)||x[2].toLowerCase().includes(nq)).slice(0,C.max).map(x=>({name:x[0],city:x[0],country:x[2],lat:x[3],lng:x[4],category:"city",references:5,rating:4.5}))}
function apply(a){const c=$("#category").value,min=+$("#rating").value||0,max=+$("#distance").value||Infinity;return a.filter(r=>(!c||String(r.category||"").includes(c))&&(r.rating||0)>=min&&(r.distance==null||r.distance<=max))}
function sorted(a){const m=$("#sort").value;return [...a].sort((x,y)=>m==="rating"?(y.rating||0)-(x.rating||0):m==="references"?(y.references||0)-(x.references||0):m==="recent"?(y.recency||0)-(x.recency||0):score(y)-score(x))}
function maps(r){return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(r.name+" "+(r.lat&&r.lng?r.lat+","+r.lng:""))}
function yt(r){return "https://www.youtube.com/results?search_query="+encodeURIComponent(r.name+" travel")}
async function videos(name, regionCode=""){
  const key=JSON.stringify({name,regionCode,o:$("#videoOrder")?.value||"relevance",d:$("#videoDuration")?.value||"",def:$("#videoDefinition")?.value||"",cap:$("#videoCaption")?.value||""});
  try{const hit=JSON.parse(sessionStorage.getItem("yt:"+key)||"null");if(hit&&Date.now()-hit.t<10*60*1000)return hit.items}catch{}
  const p=new URLSearchParams({q:name+" travel"});
  const o=$("#videoOrder")?.value||"relevance"; p.set("order",o);
  const d=$("#videoDuration")?.value; if(d)p.set("videoDuration",d);
  const def=$("#videoDefinition")?.value; if(def)p.set("videoDefinition",def);
  const cap=$("#videoCaption")?.value; if(cap)p.set("videoCaption",cap);
  if(regionCode)p.set("regionCode",regionCode);
  const r=await fetch("/.netlify/functions/youtube-search?"+p); const body=await r.json().catch(()=>({}));
  if(!r.ok){const e=Error("YouTube "+r.status);e.code=body.error||"";throw e;}
  const items=body.items||[];
  try{sessionStorage.setItem("yt:"+key,JSON.stringify({t:Date.now(),items}))}catch{}
  return items;
}
function renderVideos(items){
  const box=$("#videoResults"); if(!box)return;
  box.innerHTML=items.length?items.map(v=>'<article class="video-card"><a target="_blank" rel="noopener" href="'+v.url+'"><img src="'+esc(v.thumbnail)+'" alt=""><h3>'+esc(v.title)+'</h3></a><p>'+esc(v.channel)+' • '+Number(v.views).toLocaleString("ar")+" مشاهدة</p><button type="button" onclick="playVideo('"+esc(v.id)+"','"+esc(v.title).replace(/'/g,"&#39;")+"')">▶ مشاهدة</button></article>').join(""):'<div class="empty">لم نجد فيديوهات مناسبة.</div>';
}
async function videoSearch(query, regionCode=""){
  const q=(query||$("#q").value.trim()).trim(); if(!q)return;
  $("#videoStatus").textContent="جاري البحث عن أفضل الفيديوهات…";
  try{const items=await videos(q,regionCode);renderVideos(items);$("#videoStatus").textContent="تم العثور على "+items.length+" فيديو";$("#videoResults")?.scrollIntoView({behavior:"smooth",block:"start"})}
  catch(e){console.warn(e); const url="https://www.youtube.com/results?search_query="+encodeURIComponent(q+" travel"); const box=$("#videoResults"); if(box)box.innerHTML="<div class=\\"empty video-fallback\\"><strong>تعذر جلب النتائج المباشرة من YouTube.</strong><p>يمكنك فتح نتائج YouTube مباشرة الآن، وبعد إضافة مفتاح YouTube API ستظهر النتائج داخل الموقع.</p><a class=\\"primary\\" target=\\"_blank\\" rel=\\"noopener\\" href=\\""+url+"\\">فتح نتائج YouTube</a></div>"; $("#videoStatus").textContent=e?.code==="youtube_api_key_missing"?"مفتاح YouTube API غير مُعد في Netlify.":e?.code==="youtube_api_disabled"?"YouTube Data API v3 غير مفعّل للمفتاح.":e?.code==="youtube_quota_exceeded"?"تم تجاوز حصة YouTube API لهذا المفتاح.":"تعذر جلب فيديوهات YouTube حاليًا.";}
}
function playVideo(id,title){$("#mediaBody").innerHTML='<div class="media"><h3>'+esc(title)+'</h3><iframe loading="lazy" src="https://www.youtube.com/embed/'+encodeURIComponent(id)+'" title="'+esc(title)+'" allowfullscreen></iframe></div>';mediaDialog.showModal()}
function render(){const a=apply(sorted(S.results));$("#resultCount").textContent=a.length;$("#results").innerHTML=a.length?a.map((r,i)=>'<article class="card" id="card-'+i+'"><img class="thumb" loading="lazy" src="'+esc(r.image||"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80")+'" alt="'+esc(r.name)+'"><div class="card-body"><h3>'+esc(r.name)+'</h3><div class="meta">'+esc(r.city||"")+" "+(r.country?"• "+esc(r.country):"")+(r.rating?' • <span class="score">★ '+Number(r.rating).toFixed(1)+"</span>":"")+'</div><div class="tags"><span class="tag">'+esc(r.category||"وجهة")+'</span><span class="tag">'+(r.references||1)+" مراجع</span>"+(r.distance!=null?'<span class="tag">'+r.distance.toFixed(1)+" كم</span>":"")+'</div><div class="actions"><a class="primary" target="_blank" rel="noopener" href="'+maps(r)+'">📍 الخريطة</a><a target="_blank" rel="noopener" href="'+yt(r)+'">▶ فيديوهات</a><button type="button" onclick="showVideo('+JSON.stringify(r.name)+')">▶ عرض فيديو</button></div></div></article>').join(""):'<div class="empty">لا توجد نتائج بهذه الفلاتر.</div>';layer.clearLayers();S.markers=[];a.forEach((r,i)=>{if(!Number.isFinite(r.lat)||!Number.isFinite(r.lng))return;const m=L.marker([r.lat,r.lng]).addTo(layer).bindPopup("<b>"+esc(r.name)+"</b><br><a target='_blank' rel='noopener' href='"+maps(r)+"'>فتح في خرائط Google</a>");m.on("click",()=>$("#card-"+i)?.scrollIntoView({behavior:"smooth",block:"center"}));S.markers.push(m)});if(S.markers.length)map.fitBounds(L.featureGroup(S.markers).getBounds().pad(.18),{maxZoom:13})}
async function search(q){const id=++S.id;$("#status").textContent="جاري البحث…";let base=[];try{base=await local(q)}catch(e){console.warn("local search",e)}if(id!==S.id)return;const seen=new Set();const merge=rows=>{for(const r of rows||[]){const k=r.name+"|"+r.lat+"|"+r.lng;if(!seen.has(k)){seen.add(k);S.results.push(r)}}S.results=S.results.slice(0,C.max);render();$("#status").textContent=S.results.length?"تم جمع "+S.results.length+" نتيجة":"لم نجد نتائج مطابقة"};S.results=[];merge(base);try{const extra=await Promise.race([osm(q,$("#countryFilter").value),new Promise((_,rej)=>setTimeout(()=>rej(Error("OSM timeout")),7000))]);if(id===S.id)merge(extra)}catch(e){console.warn("OSM search",e);if(id===S.id)$("#status").textContent=S.results.length?"تم جمع "+S.results.length+" نتيجة محلية":"لم نجد نتائج مطابقة"} }
function showVideo(name){$("#mediaBody").innerHTML='<div class="media"><h3>فيديوهات: '+esc(name)+'</h3><iframe loading="lazy" src="https://www.youtube.com/embed?listType=search&list='+encodeURIComponent(name+" travel")+'" title="YouTube search"></iframe><p class="meta">يمكنك استخدام زر YouTube في البطاقة.</p></div>';mediaDialog.showModal()}
async function init(){map=L.map("map").setView([20,0],2);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);layer=L.layerGroup().addTo(map);try{const cs=await get("output/countries.json");if(Array.isArray(cs)&&cs.length){cs.sort((a,b)=>String(a.name_ar||a.name).localeCompare(String(b.name_ar||b.name),"ar")).forEach(c=>{const o=document.createElement("option");o.value=c.code;o.textContent=c.name_ar||c.name;$("#countryFilter").appendChild(o)})}}catch(e){console.warn("countries",e);[["YE","اليمن"],["SA","المملكة العربية السعودية"],["AE","الإمارات العربية المتحدة"],["TR","تركيا"],["EG","مصر"],["FR","فرنسا"],["IT","إيطاليا"],["ES","إسبانيا"],["GB","المملكة المتحدة"],["US","الولايات المتحدة"],["DE","ألمانيا"],["JP","اليابان"]].forEach(([code,name])=>{const o=document.createElement("option");o.value=code;o.textContent=name;$("#countryFilter").appendChild(o)})}$("#searchForm").addEventListener("submit",e=>{e.preventDefault();const q=$("#q").value.trim();if(q)search(q)});$("#q").addEventListener("input",()=>{clearTimeout(S.timer);S.timer=setTimeout(()=>{const q=$("#q").value.trim();if(q)search(q)},C.debounce)});document.querySelectorAll("[data-q]").forEach(b=>b.addEventListener("click",()=>{$("#q").value=b.dataset.q;search(b.dataset.q);videoSearch(b.dataset.q)}));$("#videoSearchBtn").addEventListener("click",()=>videoSearch($("#q").value.trim()));
$("#countryFilter").addEventListener("change",async()=>{const o=$("#countryFilter").selectedOptions[0];const name=o?.textContent?.trim();if(!name||!o.value)return;$("#q").value=name;search(name);videoSearch(name+" travel tourism",o.value)});["category","rating","distance","sort"].forEach(id=>$("#"+id).addEventListener("change",render));$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("tour-theme",document.body.classList.contains("light")?"light":"dark")});if(localStorage.getItem("tour-theme")==="light")document.body.classList.add("light");const q=new URLSearchParams(location.search).get("q");if(q){$("#q").value=q;search(q);videoSearch(q)}}
document.addEventListener("DOMContentLoaded",init);