const C={nominatim:"https://nominatim.openstreetmap.org/search",ttl:86400000,max:24,debounce:450};
const POPULAR=[["صنعاء","Sanaa","اليمن",15.3694,44.1910],["إسطنبول","Istanbul","تركيا",41.0082,28.9784],["القاهرة","Cairo","مصر",30.0444,31.2357],["باريس","Paris","فرنسا",48.8566,2.3522],["عدن","Aden","اليمن",12.7855,45.0187],["دبي","Dubai","الإمارات العربية المتحدة",25.2048,55.2708],["مكة","Mecca","المملكة العربية السعودية",21.3891,39.8579],["المدينة المنورة","Medina","المملكة العربية السعودية",24.5247,39.5692]];const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const S={results:[],timer:null,id:0,markers:[]};let map,layer;
function cg(k){try{const v=JSON.parse(localStorage.getItem("tour:"+k));if(v&&Date.now()-v.t<C.ttl)return v.d}catch{}return null}function cs(k,d){try{localStorage.setItem("tour:"+k,JSON.stringify({t:Date.now(),d}))}catch{}}
function score(r){return .34*(r.rating||0)/5+.24*Math.min(1,Math.log10((r.references||1)+1)/3)+.22*(r.viewsNorm||0)+.20*(r.recency||0)}
function hav(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function get(url,opts={}){const c=cg(url);if(c)return c;const r=await fetch(url,opts);if(!r.ok)throw Error("HTTP "+r.status);const d=await r.json();cs(url,d);return d}
async function osm(q){const u=C.nominatim+"?format=jsonv2&limit=20&q="+encodeURIComponent(q);const d=await get(u,{headers:{"Accept-Language":"ar"}});return d.map(x=>({name:x.display_name.split(",")[0],city:x.display_name.split(",")[1]?.trim()||"",country:x.display_name.split(",").at(-1)?.trim()||"",lat:+x.lat,lng:+x.lon,category:x.type||"place",references:3,rating:0,image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80"}))}
async function local(q){try{const code=$("#countryFilter").value;if(code){const d=await get("output/by_country/"+encodeURIComponent(code)+".json");return d.filter(x=>(x.city_ar||"").includes(q)||(x.city||"").toLowerCase().includes(q.toLowerCase())).slice(0,C.max).map(x=>({name:x.city_ar||x.city,city:x.city_ar||x.city,country:$("#countryFilter option:checked").textContent,lat:+x.lat,lng:+x.lng,category:"city",references:2,rating:0}))}const d=await get("output/cities.json");const rows=Array.isArray(d)?d:[];const hit=rows.filter(x=>(x.city_ar||"").includes(q)||(x.city||"").toLowerCase().includes(q.toLowerCase())).slice(0,C.max);if(hit.length)return hit.map(x=>({name:x.city_ar||x.city,city:x.city_ar||x.city,lat:+x.lat,lng:+x.lng,category:"city",references:2,rating:0}));return POPULAR.filter(x=>x[0].includes(q)||x[1].toLowerCase().includes(q.toLowerCase())).map(x=>({name:x[0],city:x[0],country:x[2],lat:x[3],lng:x[4],category:"city",references:5,rating:4.5}));}catch{return POPULAR.filter(x=>x[0].includes(q)||x[1].toLowerCase().includes(q.toLowerCase())).map(x=>({name:x[0],city:x[0],country:x[2],lat:x[3],lng:x[4],category:"city",references:5,rating:4.5}))}}
function apply(a){const c=$("#category").value,min=+$("#rating").value||0,max=+$("#distance").value||Infinity;return a.filter(r=>(!c||String(r.category||"").includes(c))&&(r.rating||0)>=min&&(r.distance==null||r.distance<=max))}
function sorted(a){const m=$("#sort").value;return [...a].sort((x,y)=>m==="rating"?(y.rating||0)-(x.rating||0):m==="references"?(y.references||0)-(x.references||0):m==="recent"?(y.recency||0)-(x.recency||0):score(y)-score(x))}
function maps(r){return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(r.name+" "+(r.lat&&r.lng?r.lat+","+r.lng:""))}
function yt(r){return "https://www.youtube.com/results?search_query="+encodeURIComponent(r.name+" travel")}
async function videos(name){
  const p=new URLSearchParams({q:name+" travel"});
  const o=$("#videoOrder")?.value||"relevance"; p.set("order",o);
  const d=$("#videoDuration")?.value; if(d)p.set("videoDuration",d);
  const def=$("#videoDefinition")?.value; if(def)p.set("videoDefinition",def);
  const cap=$("#videoCaption")?.value; if(cap)p.set("videoCaption",cap);
  const r=await fetch("/.netlify/functions/youtube-search?"+p); if(!r.ok)throw Error("YouTube "+r.status); return (await r.json()).items||[];
}
function renderVideos(items){
  const box=$("#videoResults"); if(!box)return;
  box.innerHTML=items.length?items.map(v=>'<article class="video-card"><a target="_blank" rel="noopener" href="'+v.url+'"><img src="'+esc(v.thumbnail)+'" alt=""><h3>'+esc(v.title)+'</h3></a><p>'+esc(v.channel)+' • '+Number(v.views).toLocaleString("ar")+" مشاهدة</p><button type="button" onclick="playVideo('"+esc(v.id)+"','"+esc(v.title).replace(/'/g,"&#39;")+"')">▶ مشاهدة</button></article>').join(""):'<div class="empty">لم نجد فيديوهات مناسبة.</div>';
}
async function videoSearch(query){
  const q=(query||$("#q").value.trim()).trim(); if(!q)return;
  $("#videoStatus").textContent="جاري البحث عن أفضل الفيديوهات…";
  try{const items=await videos(q);renderVideos(items);$("#videoStatus").textContent="تم العثور على "+items.length+" فيديو";$("#videoResults")?.scrollIntoView({behavior:"smooth",block:"start"})}
  catch(e){console.warn(e);$("#videoStatus").textContent="تعذر جلب فيديوهات YouTube. تأكد من إعداد مفتاح YouTube API في Netlify."}
}
function playVideo(id,title){$("#mediaBody").innerHTML='<div class="media"><h3>'+esc(title)+'</h3><iframe loading="lazy" src="https://www.youtube.com/embed/'+encodeURIComponent(id)+'" title="'+esc(title)+'" allowfullscreen></iframe></div>';mediaDialog.showModal()}
function render(){const a=apply(sorted(S.results));$("#resultCount").textContent=a.length;$("#results").innerHTML=a.length?a.map((r,i)=>'<article class="card" id="card-'+i+'"><img class="thumb" loading="lazy" src="'+esc(r.image||"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80")+'" alt="'+esc(r.name)+'"><div class="card-body"><h3>'+esc(r.name)+'</h3><div class="meta">'+esc(r.city||"")+" "+(r.country?"• "+esc(r.country):"")+(r.rating?' • <span class="score">★ '+Number(r.rating).toFixed(1)+"</span>":"")+'</div><div class="tags"><span class="tag">'+esc(r.category||"وجهة")+'</span><span class="tag">'+(r.references||1)+" مراجع</span>"+(r.distance!=null?'<span class="tag">'+r.distance.toFixed(1)+" كم</span>":"")+'</div><div class="actions"><a class="primary" target="_blank" rel="noopener" href="'+maps(r)+'">📍 الخريطة</a><a target="_blank" rel="noopener" href="'+yt(r)+'">▶ فيديوهات</a><button type="button" onclick="showVideo('+JSON.stringify(r.name)+')">▶ عرض فيديو</button></div></div></article>').join(""):'<div class="empty">لا توجد نتائج بهذه الفلاتر.</div>';layer.clearLayers();S.markers=[];a.forEach((r,i)=>{if(!Number.isFinite(r.lat)||!Number.isFinite(r.lng))return;const m=L.marker([r.lat,r.lng]).addTo(layer).bindPopup("<b>"+esc(r.name)+"</b><br><a target='_blank' rel='noopener' href='"+maps(r)+"'>فتح في خرائط Google</a>");m.on("click",()=>$("#card-"+i)?.scrollIntoView({behavior:"smooth",block:"center"}));S.markers.push(m)});if(S.markers.length)map.fitBounds(L.featureGroup(S.markers).getBounds().pad(.18),{maxZoom:13})}
async function search(q){const id=++S.id;$("#status").textContent="جاري تجميع النتائج…";let a=[];try{a=[...(await local(q)),...(await osm(q))]}catch(e){console.warn(e)}if(id!==S.id)return;const seen=new Set();S.results=a.filter(r=>{const k=r.name+"|"+r.lat+"|"+r.lng;if(seen.has(k))return false;seen.add(k);return true}).slice(0,C.max);render();$("#status").textContent=S.results.length?"تم جمع "+S.results.length+" نتيجة":"لم نجد نتائج مطابقة"}
function showVideo(name){$("#mediaBody").innerHTML='<div class="media"><h3>فيديوهات: '+esc(name)+'</h3><iframe loading="lazy" src="https://www.youtube.com/embed?listType=search&list='+encodeURIComponent(name+" travel")+'" title="YouTube search"></iframe><p class="meta">يمكنك استخدام زر YouTube في البطاقة.</p></div>';mediaDialog.showModal()}
async function init(){map=L.map("map").setView([20,0],2);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);layer=L.layerGroup().addTo(map);try{const cs=await get("output/countries.json");cs.sort((a,b)=>String(a.name_ar||a.name).localeCompare(String(b.name_ar||b.name),"ar")).forEach(c=>{const o=document.createElement("option");o.value=c.code;o.textContent=c.name_ar||c.name;$("#countryFilter").appendChild(o)})}catch{}$("#searchForm").addEventListener("submit",e=>{e.preventDefault();const q=$("#q").value.trim();if(q)search(q)});$("#q").addEventListener("input",()=>{clearTimeout(S.timer);S.timer=setTimeout(()=>{const q=$("#q").value.trim();if(q)search(q)},C.debounce)});document.querySelectorAll("[data-q]").forEach(b=>b.addEventListener("click",()=>{$("#q").value=b.dataset.q;search(b.dataset.q);videoSearch(b.dataset.q)}));
$("#countryFilter").addEventListener("change",async()=>{render();const o=$("#countryFilter").selectedOptions[0];const name=o?.textContent?.trim();if(name&&o.value){$("#q").value=name;videoSearch(name+" travel tourism")}});["category","rating","distance","sort"].forEach(id=>$("#"+id).addEventListener("change",render));$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("tour-theme",document.body.classList.contains("light")?"light":"dark")});if(localStorage.getItem("tour-theme")==="light")document.body.classList.add("light");const q=new URLSearchParams(location.search).get("q");if(q){$("#q").value=q;search(q)}}
document.addEventListener("DOMContentLoaded",init);